2018-12-19T12:33:44|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\logged_quantity.py", line 241, in update_value
    self.hardware_set_func(self.val)
  File "E:\LabPrograms\Python\PI_stage\pi_stage_HW_test.py", line 93, in <lambda>
    write_func = lambda new_target, n=ax_num: self.gcs.MOV(n, new_target)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcscommands.py", line 3106, in MOV
    self.__msgs.send(cmdstr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcsmessages.py", line 120, in send
    self.__checkerror(senderr=not self.__embederr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcsmessages.py", line 278, in __checkerror
    raise exc  # Raising NoneType while only classes or instances are allowed pylint: disable=E0702
pipython.gcserror.GCSError: Position out of limits (7)

2018-12-19T12:34:23|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\logged_quantity.py", line 241, in update_value
    self.hardware_set_func(self.val)
  File "E:\LabPrograms\Python\PI_stage\pi_stage_HW_test.py", line 93, in <lambda>
    write_func = lambda new_target, n=ax_num: self.gcs.MOV(n, new_target)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcscommands.py", line 3106, in MOV
    self.__msgs.send(cmdstr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcsmessages.py", line 120, in send
    self.__checkerror(senderr=not self.__embederr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcsmessages.py", line 278, in __checkerror
    raise exc  # Raising NoneType while only classes or instances are allowed pylint: disable=E0702
pipython.gcserror.GCSError: Position out of limits (7)

2018-12-19T12:34:37|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 160, in <lambda>
    op_button.clicked.connect(lambda checked, f=op_func: f())
  File "E:\LabPrograms\Python\PI_stage\pi_stage_HW_test.py", line 161, in stop
    self.gcs.STP()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcscommands.py", line 2042, in STP
    self.__msgs.send(cmdstr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcsmessages.py", line 120, in send
    self.__checkerror(senderr=not self.__embederr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pipython-1.3.4.17-py3.6.egg\pipython\gcsmessages.py", line 278, in __checkerror
    raise exc  # Raising NoneType while only classes or instances are allowed pylint: disable=E0702
pipython.gcserror.GCSError: Controller was stopped by command (10)

