2018-12-17T11:06:34|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "E:\LabPrograms\Python\PI_stage\pi_stage_HW_test.py", line 73, in connect
    stopall(self.gcs)
NameError: name 'stopall' is not defined

